### ISSUE TITLE
Doesn't serve index.html for ./

### ISSUE THREAD

**Issue by vith** [lpar/gzipped#3]

**Comment by lpar** [comment]
This is as documented: "Directory browsing isn't supported". If you wanted to add directory browsing, or at least the subset required to locate `index.html` / `index.html` / `Welcome.html`, there's a comment at line 170 of `fileserver.go` marking the location. I generally feel URL remapping is better done with a wrapper.

**Comment by vith** [comment]
I read the caveat before trying it but in combination with the "drop-in replacement" phrase I read "browsing" to mean dynamically generated file listings (func dirList). Maybe it could use a slight clarification.

**Comment by lpar** [comment]
Fair enough, I've updated the README and included an example of how to get index.html support.
