### ISSUE TITLE
Remove debug logging

### ISSUE THREAD

**Issue by hhromic** [lpar/gzipped#8]
Hi, thanks for this package, is very useful!

Can I request the removal of `fmt.Println()` debug logging from `fileserver.go`?
This produces a lot of spamming in the console during normal operations.

~~Maybe better is to use the logging mechanism from [GoLang's `log` package](https://golang.org/pkg/log/) instead?~~

EDIT: Just realised that GoLang's log package does not implement logging levels :(

**Comment by lpar** [comment]
I'm not finding any Println debug logging in v1.1.0, v2.0.0 or HEAD. Can you check what revision you're on?

I don't tend to use Go's logging because of the lack of levels. (I've got my own logger I use.)  However, any Println statements in the code are definitely there by accident.

**Comment by hhromic** [comment]
I'm using v2.0.0 but also is in current HEAD:

**v2.0.0**
https://github.com/lpar/gzipped/blob/5ee81a6d629ada4247078975412336d550d8e084/fileserver.go#L96-L105

**HEAD**
https://github.com/lpar/gzipped/blob/0420726c01cd2aa137f03c5103f4131ccde2d529/fileserver.go#L96-L105

**Comment by hhromic** [comment]
Oh my bad ! I reported `Println` when it was `Printf` ! Sorry !
